CREATE TABLE CUSTOMER (
CustomerID INT AUTO_INCREMENT PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL
);


CREATE TABLE ORDERS (
OrderCode INT AUTO_INCREMENT PRIMARY KEY,
OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
total DECIMAl(18,2) NOT NULL CHECK (total > 0),
CustomerID INT NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);

